@startuml
'https://plantuml.com/class-diagram

class ToDoList {
ToDoList: List<items> | Length: 100
}

class Item {
Description: String | Length: 1-256
Due Date: YYYY-MM-DD (Must be valid in gregorian calender)
----
}

controller -> ToDoList
ToDoList <-- Item

class controller {
AddItemClicked
DeleteItemClicked
ClearListClicked
updateDescClicked
UpdateDateClicked
MarkCompleteClicked
MarkIncompleteClicked
DisplayAllClicked
DisplayCompleteClicked
DisplayIncompleteClicked
SaveListClicked
LoadListClicked
----
itemAdd()
itemDelete()
clearList()
itemUpdateDesc()
itemUpdateDate()
itemMarkComplete()
itemMarkIncomplete()
displayAll()
displayIncomplete()
displayCompleted()
saveList()
saveText()
loadList()
}

@enduml
